---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-tcp-microk8s-conf
  namespace: ingress
data:
  8080: "devops-tools/jenkins-service:8080"
  443: "devops-tools/jenkins-service:443"
  50000: "devops-tools/jenkins-service:50000"
